import type { Product } from '@/types/product'

const BACK_WHITE = '/products/cutout/back-white.png'
const BACK_GREEN = '/products/cutout/back-green.png'
const BACK_BLACK = '/products/cutout/back-black.png'

const SHARED = {
  price: 44,
  collection: '1-800-Cyber-Love',
  status: 'pre-order' as const,
  sizes: ['S', 'M', 'L', 'XL'],
  fabric: '100% Cotton',
  fabricWeight: '260 g/m²',
  fit: 'Cropped and boxy fit.',
  modelNote: 'Model is 6\'2", 168lbs in size Medium.',
  careInstructions: [
    'Machine wash at 30°C (gentle cycle)',
    'Do not bleach',
    'Tumble dry low',
    'Iron at low temperature, avoid ironing on print',
    'Do not dry clean',
  ],
}

function description(emotion: string, colorway: string) {
  return `The "${emotion}" collection captures the four main brain states when you're trying to figure out life: Questioning, Affection, Anxiousness, and Rage. We took the classic oversized shape and gave it the digital treatment. It is not just clothing; it's a way to express yourself through your clothing.`
}

export const CYBER_LOVE_PRODUCTS: Product[] = [
  {
    ...SHARED,
    id: '1',
    emotion: 'ANXIETY',
    colorway: 'White',
    name: '"ANXIETY" — White',
    description: description('Anxiety', 'White'),
    image: '/products/cutout/anxiety-white.png',
    backImage: BACK_WHITE,
    slug: 'anxiety-white',
  },
  {
    ...SHARED,
    id: '2',
    emotion: 'LOVE',
    colorway: 'White',
    name: '"LOVE" — White',
    description: description('Love', 'White'),
    image: '/products/cutout/love-white.png',
    backImage: BACK_WHITE,
    slug: 'love-white',
  },
  {
    ...SHARED,
    id: '3',
    emotion: 'CONFUSION',
    colorway: 'White',
    name: '"CONFUSION" — White',
    description: description('Confusion', 'White'),
    image: '/products/cutout/confusion-white.png',
    backImage: BACK_WHITE,
    slug: 'confusion-white',
  },
  {
    ...SHARED,
    id: '4',
    emotion: 'RAGE',
    colorway: 'White',
    name: '"RAGE" — White',
    description: description('Rage', 'White'),
    image: '/products/cutout/rage-white.png',
    backImage: BACK_WHITE,
    slug: 'rage-white',
  },
  {
    ...SHARED,
    id: '5',
    emotion: 'ANXIETY',
    colorway: 'Army Green',
    name: '"ANXIETY" — Army Green',
    description: description('Anxiety', 'Army Green'),
    image: '/products/cutout/anxiety-green.png',
    backImage: BACK_GREEN,
    slug: 'anxiety-green',
  },
  {
    ...SHARED,
    id: '6',
    emotion: 'LOVE',
    colorway: 'Army Green',
    name: '"LOVE" — Army Green',
    description: description('Love', 'Army Green'),
    image: '/products/cutout/love-green.png',
    backImage: BACK_GREEN,
    slug: 'love-green',
  },
  {
    ...SHARED,
    id: '7',
    emotion: 'CONFUSION',
    colorway: 'Army Green',
    name: '"CONFUSION" — Army Green',
    description: description('Confusion', 'Army Green'),
    image: '/products/cutout/confusion-green.png',
    backImage: BACK_GREEN,
    slug: 'confusion-green',
  },
  {
    ...SHARED,
    id: '8',
    emotion: 'RAGE',
    colorway: 'Army Green',
    name: '"RAGE" — Army Green',
    description: description('Rage', 'Army Green'),
    image: '/products/cutout/rage-green.png',
    backImage: BACK_GREEN,
    slug: 'rage-green',
  },
]

export const BASEMENT_PRODUCTS: Product[] = [
  {
    ...SHARED,
    id: 'b1',
    emotion: 'MJ',
    colorway: 'White',
    name: '"MJ" — White',
    description: 'From The Basement.',
    image: '/products/cutout/mj-tee.png',
    backImage: BACK_WHITE,
    slug: 'mj-white',
    collection: 'Basement',
  },
  {
    ...SHARED,
    id: 'b2',
    emotion: 'ARE YOU OKAY',
    colorway: 'White',
    name: '"ARE YOU OKAY" — White',
    description: 'From The Basement.',
    image: '/products/cutout/are-you-okay-white.png',
    backImage: BACK_WHITE,
    slug: 'are-you-okay-white',
    collection: 'Basement',
  },
  {
    ...SHARED,
    id: 'b3',
    emotion: 'ARE YOU OKAY',
    colorway: 'Army Green',
    name: '"ARE YOU OKAY" — Army Green',
    description: 'From The Basement.',
    image: '/products/cutout/are-you-okay-green.png',
    backImage: BACK_GREEN,
    slug: 'are-you-okay-green',
    collection: 'Basement',
  },
  {
    ...SHARED,
    id: 'b4',
    emotion: 'ARE YOU OKAY',
    colorway: 'Black',
    name: '"ARE YOU OKAY" — Black',
    description: 'From The Basement.',
    image: '/products/cutout/are-you-okay-black.png',
    backImage: BACK_BLACK,
    slug: 'are-you-okay-black',
    collection: 'Basement',
  },
]
